### ISSUE TITLE
Add Manager Parameter to New-CT365User

### ISSUE THREAD

**Issue by DevClate** [DevClate/365AutomatedLab#16]
Make it so when a user is created it adds their manager.

**Comment by SamErde** [comment]
Great idea to include! If I recall correctly, this requires the Id of an existing user when populating a new user's manager property. Might require some error handling or a follow-up loop if not sorting the input to create managers first.

**Comment by DevClate** [comment]
> Great idea to include! If I recall correctly, this requires the Id of an existing user when populating a new user's manager property. Might require some error handling or a follow-up loop if not sorting the input to create managers first.

Thanks Sam! I believe you are right. I played with it real quick, but wanted to put it out there as well. I’m going to be adding more potential features that I’d like to add and wouldn’t mind PRs or other features 😁

**Comment by DevClate** [comment]
> Great idea to include! If I recall correctly, this requires the Id of an existing user when populating a new user's manager property. Might require some error handling or a follow-up loop if not sorting the input to create managers first.

Figured it out, cleaning it up a bit now!

**Comment by DevClate** [comment]
This has been added in 2.10.0
