### ISSUE TITLE
Enhance Microsoft Graph Connection Logic

### ISSUE THREAD

**Issue by HCRitter** [DevClate/365AutomatedLab#8]
Check out this gist, please: 
https://gist.github.com/HCRitter/8c2d082956fc5949ca119464dcec7102

Revised the code logic for establishing connections with Microsoft Graph API. The updated approach employs a switch statement to evaluate the existing context. When the context is either absent or lacks the required scopes, the script is triggered to establish a connection. The specified placeholders, 'Group.ReadWrite.All' and 'AdministrativeUnit.ReadWrite.All', will be replaced with the actual scopes during runtime. This modification is aimed at bolstering the reliability of the Microsoft Graph API connections and ensuring that requisite permissions are applied for seamless script functionality.

what do you think?

**Comment by DevClate** [comment]
Perfect, thanks for doing this!
